# [START cloudbuild_maven]
steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cusca", "--build-arg=JAR_FILE=target/cusca-1.0.0.jar", "."]
images: ["gcr.io/$PROJECT_ID/cusca"]
# [END cloudbuild_maven]